name: flutter_sparkline
description: Beautiful sparkline charts for Flutter.
version: 0.1.0
homepage: https://github.com/xqwzts/flutter_sparkline
publish_to: https://onepub.dev/api/xsvpsdavuh/

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

environment: 
  sdk: '>=3.0.2 <4.0.0'
  flutter: '>=1.17.0'
